name: Test Maven CI/CD

on:
  workflow_dispatch:

jobs:
  trigger-main:
    runs-on: ubuntu-latest
    steps:
      - name: Call Maven CI/CD Workflow
        uses: actions/github-script@v3
        with:
          script: |
            const inputs = {
              'aws-account': '739153323366', 
              'package-type': 'war'
            };
            github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'maven-ci-cd.yml',
              ref: context.ref,
              inputs: inputs
            });

