name: Test Maven CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  trigger-main:
    runs-on: ubuntu-latest
    steps:
      - name: Call Maven CI/CD Workflow
        uses: actions/checkout@v4

      - name: add 
        uses: ./.github/workflow/main.yml
        with:
          aws-account: '739153323366'
          
       

